# Generated by Django 3.1.1 on 2020-09-11 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_anime', models.CharField(max_length=400, verbose_name='Nome do anime')),
                ('ds_anime', models.CharField(max_length=600, null=True, verbose_name='Descrição do anime')),
                ('ie_assistido', models.BooleanField(default=False)),
                ('ie_favorito', models.BooleanField(default=False)),
                ('cd_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animes', to='user.usuario')),
            ],
        ),
    ]
